export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: 'products/FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'products/FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'products/FETCH_PRODUCTS_FAILED',

  SET_FILTER_START: 'products/SET_FILTER_START',
  SET_FILTER_SUCCESS: 'products/SET_FILTER_SUCCESS',
  SET_FILTER_FAILED: 'products/SET_FILTER_FAILED',
};
