const SHOP_DATA = [
  {
    title: 'Bìa hồ sơ',
    items: [
      {
        id: 1,
        name: 'Bìa còng',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/biahoso/biahoso-san-pham-1.jpg',
        price: '64000',
        prevPrice: '72000',
        description: [
          '- Độ rộng 10 cm, thân bọc simili, còng đóng, khả năng lưu trữ 500 tờ',
          '- Chức năng: lưu trữ chứng từ A4 với 2 lổ dọc thân',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Nhật Bản',
          '- Quy cách: 50 cái / thùng',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 2,
        name: 'Bìa đựng phân mục có nắp',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/biahoso/biahoso-san-pham-2.jpg',
        price: '32500',
        description: [
          '- Bìa da bọc simili, ngăn nhựa trong, khả năng lưu trữ 80 tờ',
          '- Chức năng: lưu trữ chứng từ A4, A5',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Đài Loan',
          '- Quy cách: 12 cuốn / thùng',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cuốn',
        ],
      },
      {
        id: 3,
        name: 'Phân trang nhựa',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/biahoso/biahoso-san-pham-3.jpg',
        price: '13000',
        prevPrice: '20000',
        description: [
          '- Dạng bìa nhựa, dọc thân bấm lổ, hiển thị số thứ tự (1-10)',
          '- Chức năng: phân nhóm nội dung chứng từ, sử dụng cùng với bìa còng hồ sơ',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Việt Nam',
          '- Quy cách: 5 bộ / bịch',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính:  Bộ (10 tờ)',
        ],
      },
      {
        id: 4,
        name: 'Tấm lót cắt',
        imageUrl:
          'https://github.com/binhdinhbinh57kt/data-mona-main/blob/main/assets/image/biahoso/biahoso-san-pham-4.jpg',
        price: '70000',
        prevPrice: '80000',
        description: [
          '- Bề mặt chắc, chống trượt, viền đo, phù hợp các kích cở giấy A2, A3, A4',
          '- Chức năng: Làm đế lót cắt giấy',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Đài Loan',
          '- Quy cách: 1 tấm',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Tấm',
        ],
      },
    ],
  },
  {
    title: 'Bút viết',
    items: [
      {
        id: 5,
        name: 'Bút chì lục giác Deli',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham1.jpg',
        price: '16000',
        description: [
          '- Nét vẽ mượt, ruột chì chắc, độ tương phản cao, thân gỗ tự nhiên',
          '- Chức năng: ghi chì, luyện chữ, vẽ nghệ thuật, phác họa',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Đài Loan',
          '- Quy cách: 12 cây/ hộp',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cây (12 cây / Hộp)',
        ],
      },
      {
        id: 6,
        name: 'Bút chì Đức Steadtler xanh',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham2.jpg',
        price: '16500',
        description: [
          '- Nét chữ xanh mịn đều, thân kim loại, dạng nắp đậy',
          '- Chức năng: ghi chú nội dung hội nghị',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Anh',
          '- Quy cách: 12 cây/hộp',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cây',
        ],
      },
      {
        id: 7,
        name: 'Bút lông bảng Thiên Long WB03',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham3.jpg',
        price: '7500',
        prevPrice: '10000',
        description: [
          '- Mực lông bảng, nút bấm bơm mực, nét mực rộng, mau khô',
          '- Chức năng: dùng làm dấu, ghi chú trên bề mặt không thể tẩy xóa',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '- Nsx: Việt Nam',
          '- Quy cách: cây',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cây',
        ],
      },
      {
        id: 8,
        name: 'Bút viết thư pháp',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham4.jpg',
        price: '12000',
        description: [
          '- Bút lông Deli chuyên viết thư pháp, chữ Hán',
          '- Nét bút mượt mà, ngòi bút đa dạng kích cỡ',
          '- Phù hợp với người đi làm, học sinh, sinh viên.',
          '- Nsx: Trung Quốc',
          '- Quy cách: cây',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính:  Cây',
        ],
      },
      {
        id: 9,
        name: 'Gọt bút chì',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham5.jpg',
        price: '16000',
        prevPrice: '20000',
        description: [
          '- Gọt bút chì Deli mini di động hình dạng nhỏ, không chỉ dễ sử dụng',
          '- Dao bằng thép chất lượng cao, cắt mịn',
          '- Lưỡi thép, cắt mịn, xoay nhẹ ống, phần được cạo của bút chì sẽ tự động rơi',
          '- Nsx: Việt Nam',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính:  Cái',
        ],
      },
      {
        id: 10,
        name: 'Combo 50 ruột bút',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham6.jpg',
        price: '18000',
        description: [
          '- Combo 50 ngòi ruột bút bi nước thay vào bút chữ A và bút cute',
          '- Sản phẩm là ruột bút bi nước',
          '- Có thể dùng để thay vào các bút bi nước cute khách mua ở shop hoặc bút chữ A.',
          '- Nsx: Việt Nam',
          '- Quy cách: 50 ruôt/hộp',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Hộp',
        ],
      },
      {
        id: 11,
        name: 'Set 6 bút dạ quang',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/butviet/butviet-sanpham7.jpg',
        price: '28000',
        description: [
          '- Bút dạ màu đáp ứng những yêu cầu khắt khe nhất của khách hàng',
          '- Bút dạ màu mang đến những chiếc bút với màu sắc đẹp, đảm bảo nguyên liệu cao cấp. ',
          '- Ngòi bút cứng cáp, ra mực đều luôn đảm bảo đúng kích thước, độ bền cao trong suốt thời gian sử dụng.',
          '- Nsx: Trung Quốc',
          '- Quy cách: 6 bút/hộp',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Hộp',
        ],
      },
    ],
  },
  {
    title: 'Giấy',
    items: [
      {
        id: 12,
        name: 'Ruột sổ còng',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham1.jpg',
        price: '28000',
        prevPrice: '30000',
        description: [
          '- Giấy refill có thể lồng nhiều kiểu giấy trong 1 cuốn sổ, giấy đã được đục lỗ sẵn nên rất tiện lợi cho việc ghép vào sổ.',
          '- Giấy màu trắng ngà , rất dầy dặn ,mịn, viết rất êm tay và không bị hằn lên mặt sau.',
          '- Khoảng cách các lỗ chuẩn, chuẩn xác với tất cả các dòng sổ',
          '- Nsx: Đài Loan',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 13,
        name: 'Vở ghi chép học tập',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham2.jpg',
        price: '9000',
        prevPrice: '10000',
        description: [
          '- Vở có kích thước tiêu chuẩn B5 : 251*172 ( kích thước vở chúng ta vẫn sử dụng đi học )',
          '- Chất liệu giấy đẹp, không nhòe, dễ nhìn, ăn mực',
          '- Nsx: Việt Nam',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 14,
        name: 'Tập vở kẻ ngang',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham3.jpg',
        price: '22000',
        description: [
          '- Định lượng giấy 70gsm.',
          '- Khoảng cách các dòng kẻ 8mm.',
          '- Giấy màu ngà vàng giúp giảm mỏi mỏi mắt.',
          '- Nsx: Nhật',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 15,
        name: 'Combo 10 Vở kẻ ngang',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham4.jpg',
        price: '46200',
        description: [
          '- Mặt giấy láng mịn, viết êm.',
          '- Khoảng cách các dòng kẻ 8mm.',
          '- Giấy bám mực tốt.',
          '- Gáy vở dễ dàng lật mở các trang',
          '- Nsx: Việt Nam',
          '- Quy cách: 10 quyển',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: 10 quyển',
        ],
      },
      {
        id: 16,
        name: 'Sổ ghi chép SKT 123',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham5.jpg',
        price: '15400',
        prevPrice: '16000',
        description: [
          '- Sổ ghi chép/sổ bìa da có kẹp thép vàng 4 mép chống nhăn cong giấy',
          '- Bìa da cứng dày đẹp',
          '- Tiện dụng, phù hợp cho người ghi chép, hay phải mang giấy tờ bên mình, làm sổ công thức cho các bạn học sinh...',
          '- Gáy vở dễ dàng lật mở các trang',
          '- Nsx: Việt Nam',
          '- Quy cách: quyển',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: quyển',
        ],
      },
      {
        id: 17,
        name: 'Sổ mini',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham6.jpg',
        price: '1000',
        prevPrice: '1800',
        description: [
          '- Sổ tay cute hoạt hình đẹp dễ thương, sổ tay ghi chép lò xo mini nhỏ gọn bỏ túi 80 trang a7 có dòng kẻ S05',
          '- Bìa sổ tay, sổ ghi chép  được sản xuất từ giấy bồi cứng cáp, với thiết kế nhiều mẫu dễ thương, bắt mắt',
          '- Giấy sổ tay được làm từ loại giấy chất lượng cao, độ bền cao, bề mặt giấy mềm mượt, viết êm, không thấm mực và không dễ quăn hay rách, nhàu.',
          '- Gáy vở dễ dàng lật mở các trang',
          '- Nsx: Việt Nam',
          '- Quy cách: quyển',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: quyển',
        ],
      },
      {
        id: 18,
        name: 'Sổ Plas',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/giay/giay-sanpham7.jpg',
        price: '10000',
        description: [
          '- Chất liệu bìa: nhựa PVC trong mờ, có độ bền cao, hạn chế trầy xước',
          '- 8 còng sắt chống chạm tay bằng hợp kim không gỉ, nhẹ nhưng chắc chắn',
          '- Còng được mở thủ công. Chỉ cần dùng tay mở 1 còng, các còng còn lại sẽ tự động mở theo',
          '- Nsx: Việt Nam',
          '- Quy cách: quyển',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: quyển',
        ],
      },
    ],
  },
  {
    title: 'Thước',
    items: [
      {
        id: 19,
        name: 'Thước kẻ HAKI',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham1.jpg',
        price: '24250',
        prevPrice: '31200',
        description: [
          '- Chất liệu: Nhựa',
          '- Màu Sắc : Trắng',
          '- Sản phẩm gồm 1 túi có 4 thước kẻ khác nhau.',
          '- Sản phẩm dễ thương phù hợp với nhiều mục đích sử dụng trong lĩnh vực văn phòng và học tập.',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 20,
        name: 'Thước nhựa 20cm/18cm/15cm',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham2.jpg',
        price: '4000',
        description: [
          '- Chất liệu: Nhựa',
          '- Chiều dài: 15cm, 18cm, 20cm, một bộ',
          '- Sản phẩm gồm 1 túi có 4 thước kẻ khác nhau.',
          '- Sản phẩm dễ thương phù hợp với nhiều mục đích sử dụng trong lĩnh vực văn phòng và học tập.',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 21,
        name: 'Thước kẻ trong suốt',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham3.jpg',
        price: '3000',
        prevPrice: '4500',
        description: [
          '- Chất liệu: Nhựa',
          '- Thông số kỹ thuật: thước 15cm',
          '- Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 22,
        name: 'Thước kẻ hình thú',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham4.jpg',
        price: '5400',
        description: [
          '- Chất liệu: Nhựa',
          '- Kích thước 19cm',
          '- Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 23,
        name: 'Thước kẻ có kim tuyến',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham5.jpg',
        price: '4000',
        description: [
          '- Chất liệu: Nhựa',
          '- Đặc điểm kỹ thuật: khoảng 18 * 3,8vm',
          '- Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 24,
        name: 'Thước kẻ ánh dạ quang',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham6.jpg',
        price: '7000',
        prevPrice: '8000',
        description: [
          '- Chất liệu: Nhựa',
          '- Được sản xuất từ chất liệu sắt tốt, khó gỉ, bền màu, khó hư hỏng. ',
          '- Có vạch thước rõ ràng. ',
          '- Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 25,
        name: 'Set 7 thước đo',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham7.jpg',
        price: '42000',
        description: [
          '- Chất liệu: Nhựa',
          '- Bộ bảy mảnh, chất liệu kim loại, thép không gỉ',
          '- Đường nét mịn, tỷ lệ rõ ràng, bản vẽ chính xác',
          '- Hộp kim loại, dễ dàng mang the,bền chặt',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 26,
        name: 'Bộ thước kẻ kim loại',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham8.jpg',
        price: '36000',
        description: [
          '- Chất liệu: hợp kim nhôm',
          '- Gói hàng bao gồm: thước 15cm, thước đo góc, tam giác vuông, tam giác đều ',
          '- Chất liệu kim loại, không dễ phai màu sơn ',
          '- Thang đo rõ ràng, chất liệu kim loại, dễ đo',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 27,
        name: 'Bộ 4 thước eke đóng túi',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thuoc/thuoc-sanpham10.jpg',
        price: '23000',
        prevPrice: '30500',
        description: [
          '- Chất liệu: nhựa PVC cao cấp',
          '- Thước kẻ 2 đơn vị đo inch và cm',
          '- Vạch chia rõ ràng',
          '- Phù hợp trong học tập, giảng dạy, thiết kế,....',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
    ],
  },
  {
    title: 'Cặp sách',
    items: [
      {
        id: 28,
        name: 'Balo MiniCat BL429',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-1.jpg',
        price: '73000',
        prevPrice: '110000',
        description: [
          '- Chất liệu: túi vải canvas',
          '- Kích thước: 29x8x41cm',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 29,
        name: 'Balo MiniCat BL464 ',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-2.jpg',
        price: '130000',
        description: [
          '- Chất liệu: Oxford',
          '- Kích thước: 41x28x12',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 30,
        name: 'Balo HARASHR008',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-3.jpg',
        price: '280000',
        prevPrice: '300000',
        description: [
          '- Chất liệu: Oxford',
          '- Kích thước 42cm x 30cm x 15cm.',
          '- Thiết kế hiện đại, tiện dụng',
          '- Đường may tỉ mỉ, chắc chắn',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 31,
        name: 'Balo SK 008',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-4.jpg',
        price: '200000',
        description: [
          '- Chất liệu: Oxford',
          '- Balo Kích thước : Ngang 32 cao 44 rộng 17',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Chất liệu vải Polyester 900D cao cấp dày dặn bền bỉ theo thời gian',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 32,
        name: 'Balo laptop chống sốc',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-5.jpg',
        price: '187000',
        description: [
          '- Chất liệu vải : Oxford bền bỉ. chất lượng cao, khó phai màu. ',
          '- Dễ dàng bảo quản và sử dụng được lâu dài.',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Thiết kế hiện đại và thời trang, Kiểu dáng phong cách, Dễ dàng phối đồ',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 33,
        name: 'Balo SKM 007',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tuisach/tuisach-6.jpg',
        price: '130000',
        prevPrice: '150000',
        description: [
          '- Chất liệu vải : Oxford bền bỉ. chất lượng cao, khó phai màu. ',
          '- Kích thước: Cao 47cm - Dày 17cm - Rộng 30cm',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Thiết kế hiện đại và thời trang, Kiểu dáng phong cách, Dễ dàng phối đồ',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
    ],
  },
  {
    title: 'Sản phẩm khác',
    items: [
      {
        id: 34,
        name: 'Hộp Bút Đựng Viết Mini',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-1.jpg',
        price: '33000',
        description: [
          '- Chất Liệu: Canvas',
          '- Kích Thước: 10 x 20 x 8 cm',
          '- Có 1 ngăn, có 1 ngăn nhỏ',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 35,
        name: 'Túi Đựng Bút PVC Trong Suốt',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-2.jpg',
        price: '24300',
        prevPrice: '30000',
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 20 * 8 * 3 cm',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 36,
        name: 'Dao cắt giấy',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-3.jpg',
        price: '8000',
        prevPrice: '9900',
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 22 * 60mm',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 37,
        name: 'Kệ 3 ngăn đựng đồ dùng học tập',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-4.jpg',
        price: '33500',
        description: [
          '- Chất Liệu: PVC',
          '- Kệ Nhựa chắc chắn để được nhiều đồ dùng học tập, phụ kiện.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 38,
        name: 'Ống Đựng Bút 3 Ngăn Lục Giác',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-5.jpg',
        price: '12000',
        description: [
          '- Chất Liệu: PVC',
          '- Được làm bằng chất liệu dày dặn; cứng cáp; bền đẹp cho thời gian sử dụng dài lâu.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 39,
        name: 'Thùng rác mini để bàn',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-6.jpg',
        price: '13000',
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 12.5*12.5*16.7cm.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 40,
        name: 'Bảng ghi chú mini',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/sanphamkhac/sanphamkhac-7.jpg',
        price: '42000',
        prevPrice: '45000',
        description: [
          '- Chất Liệu: Acrylic trong suốt',
          '- Bề mặt sản phẩm có lớp màng bảo vệ',
          '- Sau khi nhận có thể xé ra, độ trong suốt cao, tấm acrylic dày.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
    ],
  },
  {
    title: 'Thiết bị cho thuê',
    items: [
      {
        id: 41,
        name: 'Màn chiếu điện Exzen 150 inch',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thietbichothue/rent2.png',
        description: [
          '- Màn chiếu điện 120”x90”',
          '- Đường chéo: 150”',
          '- Kích thước: 3,05mx2,29m',
          '- Tỷ lệ màn 4:3',
          '- Chất liệu: Matte White',
          '- Motor nâng hạn điều khiển bằng remote',
          '- Dễ chịu cho người xem',
          '- Đảm bảo độ bền cao',
        ],
      },
      {
        id: 42,
        name: 'Máy Photocopy Canon IR2520W',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thietbichothue/rent3.png',
        description: [
          '- Cấu hình chuẩn: Chức năng in-copy mạng, scan màu',
          '- Khổ giấy: A3/A4',
          '- Đảo mặt bản sao: Có',
          '- ADF: Có',
          '- Cổng giao tiếp: USB/ LAN',
          '- Thu phóng: 25%-400%',
          '- Dùng mực: Sử dụng mực NPG-51: 14.600 trang A4. Tuổi thọ Drum: 132.000 trang A4.',
          '- Khay giấy dung lượng rất lớn',
          '- Kết nối tốc độ cao',
        ],
      },
      {
        id: 43,
        name: 'Máy chiếu Epson EB-S04',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thietbichothue/rent1.png',
        description: [
          '- Công nghệ: 3LCD',
          '- Độ sáng: 3000 Ansi Lumens',
          '- Độ phân giải: SVGA (800 x 600)',
          '- Độ tương phản: 15000:1',
          '- Cổng kết nối: VGA, Video, S-Video, HDMI, Wireless (Option)',
          '- Chỉnh vuông hình chiều dọc, chiều ngang: +/- 30 độ',
          '- Bóng đèn tuổi thọ 10.000 giờ',
          '- Chất lượng hình ảnh ấn tượng nhờ độ tương phản cao.',
          '- Kết nối tốc độ cao',
        ],
      },
      {
        id: 44,
        name: 'Máy in Canon LBP 2900',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/thietbichothue/rent4.png',
        description: [
          '- Độ bền cao, dễ đổ mực.',
          '- Máy in Laser A4 trắng đen.',
          '- Tốc độ in : 12-15 trang/phút',
          '- Độ phân giải : 2400 x 600 dpi',
          '- Bộ nhớ trong : 02 MB.',
          '- Khay giấy tự động : 150 tờ A4',
          '- Bản in sắc nét vượt trội',
          '- Dễ dàng sử dụng',
        ],
      },
    ],
  },
  {
    title: 'Tin mới nhất',
    items: [
      {
        id: 45,
        name: 'Làm điều quan trọng’ - sách kể bí quyết quản trị của Google',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tinmoinhat/new1.jpg',
        description: [
          'John Doerr - chuyên gia đầu tư mạo hiểm - kể phương pháp những “gã khổng lồ” áp dụng để tăng trưởng.',

          'Sách kể lại kinh nghiệm thực hành do những nhà lãnh đạo cao cấp chia sẻ. Tác giả trò chuyện ở ngôi thứ nhất. Ông bàn về chuyện hậu trường của những công ty công nghệ lớn trên thế giới như Intel, Google, Adobe, Intuit, Zume Technology…, khi họ áp dụng hệ thống thiết lập mục tiêu và kết quả chủ chốt (OKRs).',

          'Năm 1999, John Doerr gặp Larry Page và Sergey Brin - hai nhà sáng lập Google và đầu tư 12,5 triệu USD. Khi đó, Larry và Sergey sở hữu một công nghệ đột phá, tinh thần khởi nghiệp và nhiều tham vọng. Nhưng như nhiều người mới, họ không có kế hoạch kinh doanh, cách vận hành công ty bài bản. Để tồn tại, họ phải học cách quyết định giữa các lựa chọn khó khăn.',

          'John Doerr đã dạy cho Larry Page và Sergrey Brin về cách quản trị theo mục tiêu. Phương pháp này được John biết đến vào năm 1970, khi ông còn làm kỹ sư ở Intel.',

          'Theo tác giả, những mục tiêu ưu tiên hàng đầu cần đạt được với kết quả cụ thể. Tất cả mục tiêu, hoạt động được đo trong một khung thời gian định sẵn. Mục tiêu cần được chia sẻ minh bạch với toàn bộ thành viên trong tổ chức, từ nhân viên cấp thấp cho tới giám đốc điều hành. Phương pháp này giúp từng nhân viên luôn đi đúng hướng, liên kết thống nhất với cơ cấu công ty.',

          '“Đây là kinh nghiệm không chỉ dành cho các công ty công nghệ lớn, mà còn áp dụng được với các tổ chức nhỏ, công ty start-up hay cá nhân để phát triển lớn mạnh và bền vững”, tác giả chia sẻ.',

          'John Doerr là một kỹ sư, một chuyên gia đầu tư mạo hiểm và là chủ tịch của Kleiner Perkins. Trong 37 năm qua, ông giúp nhiều nhà khởi nghiệp xây dựng công ty cùng đội ngũ nhân viên. John từng là nhà đầu tư và thành viên hội đồng quản trị của Google và Amazon. Ông còn làm việc với các nhà khởi nghiệp xã hội để thay đổi tình hình giáo dục công lập, nạn đói nghèo toàn cầu.',
        ],
      },
      {
        id: 46,
        name: '‘Huế – Triều Nguyễn một cái nhìn’ qua sách Trần Đức Anh Sơn',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tinmoinhat/new2.jpg',
        description: [
          'Một hoàng cung xứ Huế hứng chịu bao nhiêu biến động thăng trầm được ghi lại như những câu chuyện còn nhiều bí ẩn.',

          'Sinh trưởng ở Huế, từng bảy năm làm giám đốc Bảo tàng Mỹ thuật Cung đình Huế, Trần Đức Anh Sơn có nhiều công trình và bài viết về cố đô để thỏa tình yêu với mảnh đất quê hương này, sách Huế – Triều Nguyễn một cái nhìn là một trong số đó.',

          'Sách tập hợp nhiều bài viết của tác giả rải rác trong các năm qua, với hai phần:Huế – di sản văn hóa và Triều Nguyễn những vấn đề lịch sử. Với cấu trúc này, tác giả Trần Đức Anh Sơn dẫn dắt người đọc qua những nơi chốn của cố đô, qua những di sản đền đài lăng tẩm, thậm chí như người hướng dẫn viên tận tâm chỉ rõ cho du khách về tính dân gian trong các trang trí thời Nguyễn, về kiến trúc độc đáo của lăng Khải Định…',

          'Dưới góc nhìn của Trần Đức Anh Sơn, Huế là một vùng đất không chỉ mang dáng vẻ cổ kính, yên bình bên bờ sông Hương mà là thành phố đang “sống” trong một phối cảnh có một hệ sinh thái riêng… Nhiều điều tự nhiên đó có ảnh hưởng quan trọng đến việc hình thành một đặc trưng văn hóa đóng vai trò không nhỏ đối với quyết định chọn kinh đô của chúa Nguyễn thời đó. Huế – thành phố dưới bóng núi Ngự – không chỉ lặng lẽ nhìn dòng Hương trôi qua mà dự phần vào lịch sử như một chứng nhân cho hai thế kỷ cuối cùng của chế độ phong kiến ở Việt Nam.',

          'Mối tương quan đó định hình cho tính cách của những người con Huế, trong đó có các vua triều Nguyễn, nghĩa là cũng liên đới đến những quyết định ảnh hưởng đến vận mệnh đất nước. Trên cái nền phong thổ ấy, một hoàng cung hiện lên hứng chịu bao nhiêu biến động thăng trầm được ghi lại trong sử sách nhưng cũng có những câu chuyện mãi chỉ là bí ẩn, trở thành giai thoại lưu truyền trong dân gian.',

          'Trong phần hai của cuốn sách: Triều Nguyễn một góc nhìn, tác giả Trần Đức Anh Sơn đặt trong tâm vào triều Nguyễn. Chính tại cố đô, năm 1806, vua Gia Long hướng tầm nhìn về phía biển Đông xác lập chủ quyền với quần đảo Hoàng Sa. Trần Đức Anh Sơn đã dẫn lại các tài liệu bằng tiếng Pháp, Italy, Đức được viết thời bấy giờ để một lần nữa khẳng định lần nữa sự công nhận của quốc tế: Quần đảo Hoàng Sa là của Việt Nam mà trong một tài liệu họ đã nhấn mạnh sự kiện năm 1816 khi vua Gia Long cho cắm cờ khẳng định chủ quyền ở đây.',

          'Sự hiện diện của hoàng tộc ở Huế sâu đậm đến mức hiện diện trong ca dao lưu truyền trong dân gian. Những câu ca dao ghi nhận những sự kiện diễn ra lúc bây giờ cũng như phản ánh phần nào cái nhìn phán xét của nhân dân với các vị vua triều Nguyễn. Dù ngày nay vua không còn nữa, những di sản họ để lại đã đi xa cái mục đích ban đầu là phục vụ cũng như thể hiện uy quyền của bậc quân vương mà đã trở thành những di sản văn hóa, thuộc về toàn dân, trở thành niềm tự hào của cư dân xứ Huế.',

          'Du khách hôm nay, khi dạo quanh hoàng cung, nhìn những món đồ, cảnh vật tĩnh tại như bấp chấp thời gian, như thể chôn vùi bao nhiêu câu chuyện. Những bức tường thành ở cố đô biết đâu còn những lời thầm thì về lịch sử một thời. Cái giai đoạn “tứ nguyệt tam vương” (bốn tháng, ba vua) biết bao rối ren khi mà thân phận một ông vua cũng chỉ như quân cờ. Những vụ tranh quyền đoạt vị, thậm chí những nghi án động trời như chuyện “vua Tự Đức thật ra là con ai?”… Những tồn nghi ấy dù có đưa ra những kiến giải nghe hết sức hữu lý thế nào vẫn khó lòng minh định.',
        ],
      },
      {
        id: 47,
        name: '‘Quyền lực mới’ – sách về sức mạnh truyền thông của mạng xã hội',
        imageUrl:
          'https://raw.githubusercontent.com/binhdinhbinh57kt/data-mona-main/main/assets/image/tinmoinhat/new3.jpg',
        description: [
          'Sách đề ra các giải pháp để nhà quản lý thu hút nguồn nhân lực trẻ và tìm phương hướng phát triển trong thời đại kỹ thuật số.',

          'Sách của Jeremy Heimans và Henry Timms vừa được dịch sang tiếng Việt. Khái niệm “quyền lực mới” được hai tác giả chứng minh bằng nhiều vụ mang tính thời sự. Chương “Tư duy quyền lực cũ, tư duy quyền lực mới”, phân tích khái niệm này thông qua scandal xâm hại tình dục của “ông trùm Hollywood” Harvey Weinstein. Ông từng có một giải Oscar trên cương vị nhà sản xuất tác phẩm Shakespeare in Love giành giải “Phim xuất sắc” năm 1999.',

          'Cơ chế “quyền lực cũ” theo hệ thống khép kín và phân cấp đã giúp Harvey Weinstein an toàn gần 30 năm. Với bề dày danh tiếng, uy tín trong nghề, Harvey Weinstein có quyền sinh sát của một ngôi sao. Truyền thông Mỹ cho rằng nhiều phụ nữ từng bị ông xâm hại đều im lặng để thoát khỏi nỗi sợ bị chèn ép trong sự nghiệp. Harvey Weinstein dùng tiền để thuê luật sự biện hộ, mua chuộc người tố cáo thậm chí thuê vệ sĩ để hăm dọa người tố cáo.',

          'Mọi chuyện đã thay đổi chỉ sau một dòng hashtag #MeToo trên Facebook của nữ diễn viên Alyssa Milano khuyến khích những người phụ nữ bị hại kể ra câu chuyện chính mình. Harvey Weinstein hầu tòa với nguy cơ lãnh mức án chung thân. Mọi chuyện không dừng lại ở đó khi nữ nghệ sĩTerri Conn tiếp tục tố cáo đạo diễn James Toback. Những “yêu râu xanh” như Kevin Spacey, Brett Ratner, danh hài Louis C.K… lần lượt lộ diện.',

          'Tác giả kết luận đến lúc cần thay đổi tư duy về khái niệm quyền lực của truyền thông. Truyền thông không chỉ gói gọn trong ý niệm một vài trang báo, các kênh nhà đài. Bất kỳ cá nhân, tổ chức tạo ra được sự lan tỏa đều có thể định hướng dư luận, thay đổi thói quen của cộng đồng.',

          'Bên cạnh việc tìm hiểu sức mạnh của các phong trào xã hội, sách còn nêu lên tầm quan trọng của quyền lực mới trong việc điều hành doanh nghiệp. Nhân sự trong lĩnh vực maketing đang loay hoay không biết làm thế nào để đạt được mục đích truyền thông hiệu quả. Các ông chủ băn khoăn tại sao nhân viên của công ty không ngừng nghỉ việc dù lương thưởng thuộc top đầu thị trường. Cùng một sản phẩm cà phê nhưng công ty A lại thành công hơn công ty B…',

          'Trong thế giới cũ, thật khó khi huy động một hay vài nhà đầu tư bỏ ra vài triệu USD cho một dự án mới nằm trong ý tưởng hoặc mới thử nghiệm. Thực tế, nhiều dự án trên thế giới thành công trong việc kêu gọi vốn cộng đồng với hàng chục triệu thậm chí vài trăm triệu USD. Từ đó cuốn sách gợi mở giúp người đọc hình thành những ý tưởng gọi vốn, phát triển dự án, tạo ra sự lan tỏa, kết nối, nhận được sự ủng hộ, phân tích những tiềm năng, thách thức khi ứng dụng vào từng công việc cụ thể.',

          'Bên cạnh tiềm năng, hai tác giả cũng cảnh báo người đọc về những nhầm tưởng. “Mới” không có nghĩa là tốt và “cũ” không có nghĩa là xấu. Chương sách mang tên “Chuyển hướng từ quyền lực cũ sang quyền lực mới” như một bảng hướng dẫn cho sự chuyển giao. Henry và Jeremy chia sẻ khi cộng đồng nhiều “nhà đầu tư” nghĩa là dự án có nhiều “ông chủ”. Dự án có thể phải đối mặt với những đả kích từ nhiều luồng ý kiến khác nhau. Nếu không cẩn thận, từ một dự án, chiến lược ủng hộ có thể bị tẩy chay, trù dập bất kỳ lúc nào. Chủ dự án có thể không bao giờ gây quỹ được nữa.',
        ],
      },
    ],
  },
];
