const SHOP_DATA = [
  {
    title: 'Bìa hồ sơ',
    items: [
      {
        id: 1,
        name: 'Bìa còng King Jim 10f',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 64,
        description: [
          '- Độ rộng 10 cm, thân bọc simili, còng đóng, khả năng lưu trữ 500 tờ',
          '- Chức năng: lưu trữ chứng từ A4 với 2 lổ dọc thân',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Nhật Bản',
          '– Quy cách: 50 cái / thùng',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 2,
        name: 'Bìa đựng hồ sơ phân mục có nắp',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 32,
        description: [
          '– Bìa da bọc simili, ngăn nhựa trong, khả năng lưu trữ 80 tờ',
          '– Chức năng: lưu trữ chứng từ A4, A5',
          '– Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Đài Loan',
          '– Quy cách: 12 cuốn / thùng',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cuốn',
        ],
      },
      {
        id: 3,
        name: 'Phân trang nhựa',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 13,
        description: [
          '– Dạng bìa nhựa, dọc thân bấm lổ, hiển thị số thứ tự (1-10)',
          '– Chức năng: phân nhóm nội dung chứng từ, sử dụng cùng với bìa còng hồ sơ',
          '– Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Việt Nam',
          '– Quy cách: 5 bộ / bịch',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Bộ (10 tờ)',
        ],
      },
      {
        id: 4,
        name: 'Tấm lót cắt',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 70,
        description: [
          '– Bề mặt chắc, chống trượt, viền đo, phù hợp các kích cở giấy A2, A3, A4',
          '– Chức năng: Làm đế lót cắt giấy',
          '– Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Đài Loan',
          '– Quy cách: 1 cái / bộ',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Tấm',
        ],
      },
    ],
  },
  {
    title: 'Bút viết',
    items: [
      {
        id: 5,
        name: 'Bút chì lục giác Deli',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 16,
        description: [
          '– Nét vẽ mượt, ruột chì chắc, độ tương phản cao, thân gỗ tự nhiên',
          '– Chức năng: ghi chì, luyện chữ, vẽ nghệ thuật, phác họa',
          '- Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Đài Loan',
          '– Quy cách: 12 cây / hộp',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Cây (12 cây / Hộp)',
        ],
      },
      {
        id: 6,
        name: 'Bút chì Đức Steadtler xanh',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 16,
        description: [
          '– Nét chữ xanh mịn đều, thân kim loại, dạng nắp đậy',
          '– Chức năng: ghi chú nội dung hội nghị',
          '– Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Anh',
          '– Quy cách: 12 cây / hộp',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Cây',
        ],
      },
      {
        id: 7,
        name: 'Bút lông bảng Thiên Long WB03',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 7.5,
        description: [
          '– Mực lông bảng, nút bấm bơm mực, nét mực rộng, mau khô',
          '– Chức năng: dùng làm dấu, ghi chú trên bề mặt không thể tẩy xóa',
          '– Đáp ứng tiêu chuẩn sức khỏe người dùng văn phòng',
          '– Nsx: Việt Nam',
          '– Quy cách: cây',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Cây',
        ],
      },
      {
        id: 8,
        name: 'Bút viết thư pháp chữ Hán Calligraphy Deli',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 12,
        description: [
          '– Bút lông Deli chuyên viết thư pháp, chữ Hán',
          '– Nét bút mượt mà, ngòi bút đa dạng kích cỡ',
          '– Phù hợp với người đi làm, học sinh, sinh viên.',
          '– Nsx: Trung Quốc',
          '– Quy cách: cây',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Cây',
        ],
      },
      {
        id: 9,
        name: 'Gọt bút chì Deli UARELIFFE',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 16,
        description: [
          '– Gọt bút chì Deli mini di động hình dạng nhỏ, không chỉ dễ sử dụng',
          '– Dao bằng thép chất lượng cao, cắt mịn',
          '– Lưỡi thép, cắt mịn, xoay nhẹ ống, phần được cạo của bút chì sẽ tự động rơi',
          '– Nsx: Việt Nam',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính:  Cái',
        ],
      },
      {
        id: 10,
        name: 'Combo 50 ruột bút,ngòi bút bi nước Thay Thế Bút Chữ A Tiện Dụng',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 18,
        description: [
          '– Combo 50 ngòi ruột bút bi nước thay vào bút chữ A và bút cute',
          '– Sản phẩm là ruột bút bi nước',
          '– Có thể dùng để thay vào các bút bi nước cute khách mua ở shop hoặc bút chữ A.',
          '– Nsx: Việt Nam',
          '– Quy cách: 50 ruôt/hộp',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Hộp',
        ],
      },
      {
        id: 11,
        name: 'Set 6 bút dạ quang dùng để đánh dấu dành cho học sinh',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 28,
        description: [
          '– Bút dạ màu đáp ứng những yêu cầu khắt khe nhất của khách hàng',
          '– Bút dạ màu mang đến những chiếc bút với màu sắc đẹp, đảm bảo nguyên liệu cao cấp. ',
          '– Ngòi bút cứng cáp, ra mực đều luôn đảm bảo đúng kích thước, độ bền cao trong suốt thời gian sử dụng.',
          '– Nsx: Trung Quốc',
          '– Quy cách: 6 bút/hộp',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Hộp',
        ],
      },
    ],
  },
  {
    title: 'Giấy',
    items: [
      {
        id: 12,
        name: 'Ruột sổ còng giấy refill HAKI 20 26 30 lỗ A5 B5 A4 sổ planner bullet journal',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 28,
        description: [
          '– Giấy refill có thể lồng nhiều kiểu giấy trong 1 cuốn sổ, giấy đã được đục lỗ sẵn nên rất tiện lợi cho việc ghép vào sổ.',
          '– Giấy màu trắng ngà , rất dầy dặn ,mịn, viết rất êm tay và không bị hằn lên mặt sau.',
          '- Khoảng cách các lỗ chuẩn, chuẩn xác với tất cả các dòng sổ',
          '– Nsx: Đài Loan',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 13,
        name: 'Vở ghi chép học tập bìa in hình gấu dễ thương kích thước phổ thông ( 60 trang )',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 9,
        description: [
          '– Vở có kích thước tiêu chuẩn B5 : 251*172 ( kích thước vở chúng ta vẫn sử dụng đi học )',
          '– Chất liệu giấy đẹp, không nhòe, dễ nhìn, ăn mực',
          '– Nsx: Việt Nam',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 14,
        name: 'Tập vở kẻ ngang TAKEYO B5 A4 - Vở khâu gáy takeyo giấy ngà vàng',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 22,
        description: [
          '– Định lượng giấy 70gsm.',
          '– Khoảng cách các dòng kẻ 8mm.',
          '– Giấy màu ngà vàng giúp giảm mỏi mỏi mắt.',
          '– Nsx: Nhật',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 15,
        name: 'Combo 10 Vở kẻ ngang HẢI TIẾN 72 trang, 120 trang, giấy không bụi',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 46,
        description: [
          '– Mặt giấy láng mịn, viết êm.',
          '– Khoảng cách các dòng kẻ 8mm.',
          '– Giấy bám mực tốt.',
          '– Gáy vở dễ dàng lật mở các trang',
          '– Nsx: Việt Nam',
          '– Quy cách: 10 quyển',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: 10 quyển',
        ],
      },
      {
        id: 16,
        name: 'Sổ ghi chép B3 Hải tiến bìa cứng 120 trang',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 15,
        description: [
          '– Sổ ghi chép/sổ bìa da có kẹp thép vàng 4 mép chống nhăn cong giấy',
          '– Bìa da cứng dày đẹp',
          '– Tiện dụng, phù hợp cho người ghi chép, hay phải mang giấy tờ bên mình, làm sổ công thức cho các bạn học sinh...',
          '– Gáy vở dễ dàng lật mở các trang',
          '– Nsx: Việt Nam',
          '– Quy cách: quyển',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: quyển',
        ],
      },
      {
        id: 17,
        name: 'Sổ lò xo mini ngẫu nhiên (F3A01)',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 1,
        description: [
          '– Sổ tay cute hoạt hình đẹp dễ thương, sổ tay ghi chép lò xo mini nhỏ gọn bỏ túi 80 trang a7 có dòng kẻ S05',
          '– Bìa sổ tay, sổ ghi chép  được sản xuất từ giấy bồi cứng cáp, với thiết kế nhiều mẫu dễ thương, bắt mắt',
          '– Giấy sổ tay được làm từ loại giấy chất lượng cao, độ bền cao, bề mặt giấy mềm mượt, viết êm, không thấm mực và không dễ quăn hay rách, nhàu.',
          '– Gáy vở dễ dàng lật mở các trang',
          '– Nsx: Việt Nam',
          '– Quy cách: quyển',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: quyển',
        ],
      },
      {
        id: 18,
        name: 'Sổ Plas A5 B5 sổ tay lò xo bìa lá 70 tờ',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 10,
        description: [
          '– Chất liệu bìa: nhựa PVC trong mờ, có độ bền cao, hạn chế trầy xước',
          '– 8 còng sắt chống chạm tay bằng hợp kim không gỉ, nhẹ nhưng chắc chắn',
          '– Còng được mở thủ công. Chỉ cần dùng tay mở 1 còng, các còng còn lại sẽ tự động mở theo',
          '– Nsx: Việt Nam',
          '– Quy cách: quyển',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: quyển',
        ],
      },
    ],
  },
  {
    title: 'Thước',
    items: [
      {
        id: 19,
        name: 'Thước kẻ cute HAKI bộ 4 món có túi đựng họa tiết hoạt hình dễ thương cho học sinh TK03',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 28,
        description: [
          '– Chất liệu: Nhựa',
          '– Màu Sắc : Trắng',
          '– Sản phẩm gồm 1 túi có 4 thước kẻ khác nhau.',
          '– Sản phẩm dễ thương phù hợp với nhiều mục đích sử dụng trong lĩnh vực văn phòng và học tập.',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 20,
        name: 'Thước nhựa 20cm / 18cm / 15cm thiết kế dễ nhìn đơn giản chất lượng cao',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 4,
        description: [
          '– Chất liệu: Nhựa',
          '– Chiều dài: 15cm, 18cm, 20cm, một bộ',
          '– Sản phẩm gồm 1 túi có 4 thước kẻ khác nhau.',
          '– Sản phẩm dễ thương phù hợp với nhiều mục đích sử dụng trong lĩnh vực văn phòng và học tập.',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 21,
        name: 'Thước Kẻ Trong Suốt 15cm Hình Phi Hành Gia Độc Đáo Sáng Tạo',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 3,
        description: [
          '– Chất liệu: Nhựa',
          '– Thông số kỹ thuật: thước 15cm',
          '– Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 22,
        name: 'Thước kẻ đầu thú dễ thương',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 4,
        description: [
          '– Chất liệu: Nhựa',
          '– Kích thước 19cm',
          '– Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 23,
        name: 'Thước Kẻ Họa Tiết Hoạt Hình Có Kim Tuyến Nước Dễ Thương 15cm',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 4,
        description: [
          '– Chất liệu: Nhựa',
          '– Đặc điểm kỹ thuật: khoảng 18 * 3,8vm',
          '– Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 24,
        name: 'Thước kẻ ánh dạ quang Deli 20cm',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 7,
        description: [
          '– Chất liệu: Nhựa',
          '– Được sản xuất từ chất liệu sắt tốt, khó gỉ, bền màu, khó hư hỏng. ',
          '– Có vạch thước rõ ràng. ',
          '– Dành cho: học ở trường, kế hoạch hàng ngày, quà tặng, văn phòng',
          '– Nsx: Trung Quốc',
          '– Quy cách: cái',
          '– Tiết kiệm hơn khi chọn mua theo nhóm',
          '– Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '– Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '– Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '– Đơn vị tính: Cái',
        ],
      },
      {
        id: 24,
        name: 'Set 7 thước đo hình học chuyên dụng Tổ hợp thước',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 42,
        description: [
          '- Chất liệu: Nhựa',
          '- Bộ bảy mảnh, chất liệu kim loại, thép không gỉ. ',
          '- Đường nét mịn, tỷ lệ rõ ràng, bản vẽ chính xác ',
          '- Hộp kim loại, dễ dàng mang the,bền chặt',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 24,
        name: 'Set 7 thước đo hình học chuyên dụng Tổ hợp thước',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 42,
        description: [
          '- Chất liệu: Nhựa',
          '- Bộ bảy mảnh, chất liệu kim loại, thép không gỉ. ',
          '- Đường nét mịn, tỷ lệ rõ ràng, bản vẽ chính xác ',
          '- Hộp kim loại, dễ dàng mang the,bền chặt',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 25,
        name: 'Bộ thước kẻ bằng kim loại cao cấp tiện lợi cho học sinh',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 42,
        description: [
          '- Chất liệu: hợp kim nhôm',
          '- Gói hàng bao gồm: thước 15cm, thước đo góc, tam giác vuông, tam giác đều ',
          '- Chất liệu kim loại, không dễ phai màu sơn ',
          '- Thang đo rõ ràng, chất liệu kim loại, dễ đo',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 26,
        name: 'Bộ 4 thước đo đa năng bằng hợp kim nhôm tiện lợi YS-6209',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 42,
        description: [
          '- Chất liệu: hợp kim nhôm',
          '- Kích thước sản phẩm: 15cm ',
          '- Phong cách: Thước kẻ/ Thước tam giác/ Thước đo góc ',
          '- Thang đo rõ ràng, chất liệu kim loại, dễ đo',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
      {
        id: 27,
        name: 'Bộ 4 thước eke đóng túi kích thước 20cm',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 42,
        description: [
          '- Chất liệu: nhựa PVC cao cấp',
          '- Thước kẻ 2 đơn vị đo inch và cm',
          '- Vạch chia rõ ràng',
          '- Phù hợp trong học tập, giảng dạy, thiết kế,....',
          '- Nsx: Trung Quốc',
          '- Quy cách: cái',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Cái',
        ],
      },
    ],
  },
  {
    title: 'Cặp sách',
    items: [
      {
        id: 28,
        name: 'Balo đi học giá rẻ thời trang cute đẹp TEESHOP BL007',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 73,
        description: [
          '- Chất liệu: túi vải canvas',
          '- Kích thước: 29x8x41cm',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 29,
        name: 'Balo du lịch đi học giá rẻ thời trang cute đẹp MiniCat BL464 ',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất liệu: Oxford',
          '- Kích thước: 41x28x12',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 30,
        name: 'Balo Hàn Quốc cao cấp HARASHR008',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất liệu: Oxford',
          '- Kích thước 42cm x 30cm x 15cm.',
          '- Thiết kế hiện đại, tiện dụng',
          '- Đường may tỉ mỉ, chắc chắn',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 31,
        name: 'Balo thời trang nam nữ, SK 008, balo đi học ,balo đựng laptop, balo nữ',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất liệu: Oxford',
          '- Balo Kích thước : Ngang 32 cao 44 rộng 17',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Chất liệu vải Polyester 900D cao cấp dày dặn bền bỉ theo thời gian',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 32,
        name: 'Balo laptop chống sốc',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất liệu vải : Oxford bền bỉ. chất lượng cao, khó phai màu. ',
          '- Dễ dàng bảo quản và sử dụng được lâu dài.',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Thiết kế hiện đại và thời trang, Kiểu dáng phong cách, Dễ dàng phối đồ',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 33,
        name: 'Balo Đi Học, Balô Túi Thời Trang Nam Nữ Học Sinh Sinh Viên Đẹp Giá Rẻ',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất liệu vải : Oxford bền bỉ. chất lượng cao, khó phai màu. ',
          '- Kích thước: Cao 47cm - Dày 17cm - Rộng 30cm',
          '- Balo có tổng 7 ngăn, có ngăn đựng laptop',
          '- Thiết kế hiện đại và thời trang, Kiểu dáng phong cách, Dễ dàng phối đồ',
          '- Bên trong balo có lớp lót chống thấm. đệm mút dày 7T giúp ta đeo nhiều giờ không bị nhức mỏi',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
    ],
  },
  {
    title: 'Sản phẩm khác',
    id: 6,
    items: [
      {
        id: 34,
        name: 'Hộp Bút Đựng Viết Mini Nam Nữ Siêu Bền Đẹp local brand M Studio',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: Canvas',
          '- Kích Thước: 10 x 20 x 8 cm',
          '- Có 1 ngăn, có 1 ngăn nhỏ',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 35,
        name: 'Túi Đựng Bút Bằng PVC Trong Suốt Có Khóa Kéo In Họa Tiết Chữ Letit',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 20 * 8 * 3 cm	',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 36,
        name: 'Dao cắt giấy',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 22 * 60mm',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 37,
        name: 'Kệ 3 Ngăn, Kệ Đựng Bút, Đồ Dùng Học Tập',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: PVC',
          '- Kệ Nhựa chắc chắn để được nhiều đồ dùng học tập, phụ kiện.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 38,
        name: 'Ống Đựng Bút 3 Ngăn Lục Giác',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: PVC',
          '- Được làm bằng chất liệu dày dặn; cứng cáp; bền đẹp cho thời gian sử dụng dài lâu.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 39,
        name: 'Thùng rác bằng nhựa để bàn nhỏ gọn tiện dụng và bền',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: PVC',
          '- Kích thước: 12.5*12.5*16.7cm.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
      {
        id: 40,
        name: 'Bảng ghi chú mini bằng Acrylic trong suốt',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 130,
        description: [
          '- Chất Liệu: Acrylic',
          '- Bề mặt sản phẩm có lớp màng bảo vệ',
          '- Sau khi nhận có thể xé ra, độ trong suốt cao, tấm acrylic dày.',
          '- Nsx: Trung Quốc',
          '- Quy cách: chiếc',
          '- Tiết kiệm hơn khi chọn mua theo nhóm',
          '- Chương trình khuyến mãi chỉ áp dụng cho các đơn hàng trực tuyến',
          '- Vận chuyển miễn phí dựa trên giá trị đơn hàng',
          '- Mẫu mã và thông tin sản phẩm có thể thay đổi theo chính sách nhà sản xuất',
          '- Đơn vị tính: Chiếc',
        ],
      },
    ],
  },
];
